### ISSUE TITLE
NoClassDefFoundError: jodd/csselly/CSSellyException with Geb 5.1

### ISSUE THREAD

**Issue by joergrech** [geb/issues#650]
Since updating to 5.1 I'm getting the following Exception in a Docker container running a Gradle project using Geb:

```java
2021-12-21 11:03:48.556 INFO  AWebTester - Starting Chrome headless
ChromeDriver was started successfully.
Exception in thread "main" java.lang.NoClassDefFoundError: jodd/csselly/CSSellyException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.lambda$createCallStaticSite$2(CallSiteArray.java:65)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:63)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:156)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at geb.navigator.DefaultNavigator$_matchingSelectorAndPredicates_closure62.doCall(DefaultNavigator.groovy:1112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:49)
	at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:52)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4971)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4843)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4828)
	at org.codehaus.groovy.runtime.dgm$246.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at geb.navigator.DefaultNavigator$_parent_closure33$_closure84.doCall(DefaultNavigator.groovy:485)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at geb.navigator.DefaultNavigator$_collectRelativeElements_closure60.doCall(DefaultNavigator.groovy:1076)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at geb.navigator.DefaultNavigator$_collectElements_closure57.doCall(DefaultNavigator.groovy:1044)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2331)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2316)
	at org.codehaus.groovy.runtime.dgm$198.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at geb.navigator.DefaultNavigator.collectElements(DefaultNavigator.groovy:1042)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at geb.navigator.DefaultNavigator.collectRelativeElements(DefaultNavigator.groovy:1074)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at geb.navigator.DefaultNavigator.collectParents(DefaultNavigator.groovy:1089)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at geb.navigator.DefaultNavigator$_parent_closure33.doCall(DefaultNavigator.groovy:484)
	at geb.navigator.DefaultNavigator$_parent_closure33.doCall(DefaultNavigator.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
	at com.sun.proxy.$Proxy46.get(Unknown Source)
	at java_util_function_Supplier$get.call(Unknown Source)
	at geb.navigator.DefaultNavigator.navigatorFor(DefaultNavigator.groovy:866)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:226)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at geb.navigator.DefaultNavigator.parent(DefaultNavigator.groovy:483)
	at geb.navigator.DefaultNavigator.parent(DefaultNavigator.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1120)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.DelegatingMetaClass.invokeMethod(DelegatingMetaClass.java:147)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:96)
... (here starts my code)
```

the entry point in my code is:

```java
def test = browser?.find("[id*=CompanyProfile] a > div > svg[width='11']")?.first()?.parent("a")?.attr("href")
```

`gradle dependencies`gives me the following for Geb:
```
+--- org.gebish:geb-core:5.1
|    +--- org.jodd:jodd-lagarto:5.1.5
|    |    +--- org.jodd:jodd-log:5.1.5
|    |    |    +--- org.slf4j:slf4j-api:[1.7,1.8) -> 1.7.32
|    |    |    +--- commons-logging:commons-logging:[1.2,1.3) -> 1.2
|    |    |    \--- org.apache.logging.log4j:log4j-api:[2.8,2.9) -> 2.17.0
|    |    \--- org.jodd:jodd-core:5.1.5
|    +--- org.seleniumhq.selenium:selenium-api:3.141.59 -> 4.1.0
|    +--- org.gebish:geb-ast:5.1
|    |    +--- org.codehaus.groovy:groovy-bom:3.0.8
|    |    |    +--- org.codehaus.groovy:groovy:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-ant:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-astbuilder:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-cli-picocli:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-console:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-datetime:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-docgenerator:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-groovydoc:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-groovysh:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-jmx:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-json:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-jsr223:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-macro:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-nio:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-servlet:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-sql:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-swing:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-templates:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-test:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-test-junit5:3.0.8 (c)
|    |    |    +--- org.codehaus.groovy:groovy-testng:3.0.8 (c)
|    |    |    \--- org.codehaus.groovy:groovy-xml:3.0.8 (c)
|    |    +--- org.codehaus.groovy:groovy -> 3.0.8
|    |    +--- org.codehaus.groovy:groovy-templates -> 3.0.8 (*)
|    |    \--- org.codehaus.groovy:groovy-macro -> 3.0.8 (*)
|    +--- org.gebish:geb-waiting:5.1
|    |    +--- org.gebish:geb-implicit-assertions:5.1
|    |    |    +--- org.codehaus.groovy:groovy-bom:3.0.8 (*)
|    |    |    +--- org.codehaus.groovy:groovy -> 3.0.8
|    |    |    \--- org.codehaus.groovy:groovy-templates -> 3.0.8 (*)
|    |    +--- org.gebish:geb-exceptions:5.1
|    |    |    +--- org.codehaus.groovy:groovy-bom:3.0.8 (*)
|    |    |    +--- org.codehaus.groovy:groovy -> 3.0.8
|    |    |    \--- org.codehaus.groovy:groovy-templates -> 3.0.8 (*)
|    |    +--- org.codehaus.groovy:groovy-bom:3.0.8 (*)
|    |    +--- org.codehaus.groovy:groovy -> 3.0.8
|    |    \--- org.codehaus.groovy:groovy-templates -> 3.0.8 (*)
|    +--- org.threeten:threeten-extra:1.4
|    +--- org.codehaus.groovy:groovy-bom:3.0.8 (*)
|    +--- org.codehaus.groovy:groovy -> 3.0.8
|    \--- org.codehaus.groovy:groovy-templates -> 3.0.8 (*)
```
Any ideas how to fix this dependency problem?

**Comment by erdi** [comment]
Thanks for reporting. I will investigate over the next two days, @joergrech, and let you know.

**Comment by erdi** [comment]
I had a look at this and I have no idea why you are getting a `NoClassDefFoundError` for `jodd/csselly/CSSellyException`. That class is part of `org.jodd:jodd-lagarto` which according to the `gradle dependencies` output you provided should be on your classpath. Moreover, there is [test coverage for the code path that is errorring for you](https://github.com/geb/geb/blob/92c0f481984333da7d5df7faecfad2867a6c66bc/doc/manual-snippets/src/test/groovy/navigator/TraversingSpec.groovy#L101) and all of the tests passed prior to doing the 5.1 release.

All of the above makes me think that this will unfortunately for you be specific to your environment. Is there any unusual class loading involved in how you are running your tests? Has this started to happen after you upgraded Geb? Can you provide a standalone project which would reproduce the issue? Unfortunately I might have to close this issue unless you can provide more information which would help me to reproduce it on my end.

**Comment by erdi** [comment]
Closing due to no response from the OP. Feel free to reopen with more info if it's still an issue.
